/**
 * Achievement Definitions
 * Contains 80+ achievement configurations across 5 categories
 * Task: T112 [US8]
 */

import type { Achievement, AchievementCategory, AchievementTier } from '@/types/achievement';

/**
 * Achievement reward tiers
 */
const TIER_REWARDS: Record<AchievementTier, { xp: number; currency: number }> = {
    bronze: { xp: 250, currency: 25 },
    silver: { xp: 500, currency: 50 },
    gold: { xp: 1000, currency: 100 },
    platinum: { xp: 2000, currency: 250 },
    diamond: { xp: 5000, currency: 500 },
};

/**
 * Combat Achievements
 * Track wins, damage, combos, and combat mastery
 */
export const COMBAT_ACHIEVEMENTS: Achievement[] = [
    // Bronze - Entry level
    {
        id: 'c01',
        name: 'First Blood',
        description: 'Win your first match',
        category: 'combat',
        tier: 'bronze',
        iconUrl: '/assets/achievements/first_blood.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 1, trackingKey: 'total_wins' },
        isSecret: false,
        displayOrder: 1,
    },
    {
        id: 'c02',
        name: 'Combo Starter',
        description: 'Execute 10 combo sequences',
        category: 'combat',
        tier: 'bronze',
        iconUrl: '/assets/achievements/combo_starter.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 10, trackingKey: 'total_combos' },
        isSecret: false,
        displayOrder: 2,
    },
    {
        id: 'c03',
        name: 'Damage Dealer',
        description: 'Deal 1,000 total damage',
        category: 'combat',
        tier: 'bronze',
        iconUrl: '/assets/achievements/damage_dealer.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 1000, trackingKey: 'total_damage_dealt' },
        isSecret: false,
        displayOrder: 3,
    },
    {
        id: 'c04',
        name: 'Block Master',
        description: 'Block 25 attacks',
        category: 'combat',
        tier: 'bronze',
        iconUrl: '/assets/achievements/block_master.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 25, trackingKey: 'total_blocks' },
        isSecret: false,
        displayOrder: 4,
    },
    // Silver - Intermediate
    {
        id: 'c05',
        name: 'Warrior',
        description: 'Win 10 matches',
        category: 'combat',
        tier: 'silver',
        iconUrl: '/assets/achievements/warrior.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 10, trackingKey: 'total_wins' },
        isSecret: false,
        displayOrder: 5,
    },
    {
        id: 'c06',
        name: 'Combo Artist',
        description: 'Execute 50 combo sequences',
        category: 'combat',
        tier: 'silver',
        iconUrl: '/assets/achievements/combo_artist.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 50, trackingKey: 'total_combos' },
        isSecret: false,
        displayOrder: 6,
    },
    {
        id: 'c07',
        name: 'Destruction',
        description: 'Deal 10,000 total damage',
        category: 'combat',
        tier: 'silver',
        iconUrl: '/assets/achievements/destruction.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 10000, trackingKey: 'total_damage_dealt' },
        isSecret: false,
        displayOrder: 7,
    },
    {
        id: 'c08',
        name: 'Perfect Round',
        description: 'Win a round without taking damage',
        category: 'combat',
        tier: 'silver',
        iconUrl: '/assets/achievements/perfect_round.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 1, trackingKey: 'perfect_rounds' },
        isSecret: false,
        displayOrder: 8,
    },
    // Gold - Advanced
    {
        id: 'c09',
        name: 'Champion',
        description: 'Win 50 matches',
        category: 'combat',
        tier: 'gold',
        iconUrl: '/assets/achievements/champion.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'counter', targetValue: 50, trackingKey: 'total_wins' },
        isSecret: false,
        displayOrder: 9,
    },
    {
        id: 'c10',
        name: 'Combo Master',
        description: 'Execute 200 combo sequences',
        category: 'combat',
        tier: 'gold',
        iconUrl: '/assets/achievements/combo_master.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'counter', targetValue: 200, trackingKey: 'total_combos' },
        isSecret: false,
        displayOrder: 10,
    },
    {
        id: 'c11',
        name: 'Win Streak 5',
        description: 'Win 5 matches in a row',
        category: 'combat',
        tier: 'gold',
        iconUrl: '/assets/achievements/win_streak_5.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'milestone', targetValue: 5, trackingKey: 'win_streak' },
        isSecret: false,
        displayOrder: 11,
    },
    {
        id: 'c12',
        name: 'Perfect Match',
        description: 'Win a match with 3 perfect rounds',
        category: 'combat',
        tier: 'gold',
        iconUrl: '/assets/achievements/perfect_match.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'milestone', targetValue: 3, trackingKey: 'perfect_rounds_in_match' },
        isSecret: false,
        displayOrder: 12,
    },
    // Platinum - Expert
    {
        id: 'c13',
        name: 'Legend',
        description: 'Win 100 matches',
        category: 'combat',
        tier: 'platinum',
        iconUrl: '/assets/achievements/legend.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'counter', targetValue: 100, trackingKey: 'total_wins' },
        isSecret: false,
        displayOrder: 13,
    },
    {
        id: 'c14',
        name: 'Win Streak 10',
        description: 'Win 10 matches in a row',
        category: 'combat',
        tier: 'platinum',
        iconUrl: '/assets/achievements/win_streak_10.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'milestone', targetValue: 10, trackingKey: 'win_streak' },
        isSecret: false,
        displayOrder: 14,
    },
    {
        id: 'c15',
        name: 'Devastator',
        description: 'Deal 100,000 total damage',
        category: 'combat',
        tier: 'platinum',
        iconUrl: '/assets/achievements/devastator.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'counter', targetValue: 100000, trackingKey: 'total_damage_dealt' },
        isSecret: false,
        displayOrder: 15,
    },
    // Diamond - Master
    {
        id: 'c16',
        name: 'Immortal',
        description: 'Win 500 matches',
        category: 'combat',
        tier: 'diamond',
        iconUrl: '/assets/achievements/immortal.png',
        xpReward: TIER_REWARDS.diamond.xp,
        currencyReward: TIER_REWARDS.diamond.currency,
        requirement: { type: 'counter', targetValue: 500, trackingKey: 'total_wins' },
        isSecret: false,
        displayOrder: 16,
    },
    {
        id: 'c17',
        name: 'Flawless Fighter',
        description: 'Win 10 perfect matches',
        category: 'combat',
        tier: 'diamond',
        iconUrl: '/assets/achievements/flawless_fighter.png',
        xpReward: TIER_REWARDS.diamond.xp,
        currencyReward: TIER_REWARDS.diamond.currency,
        requirement: { type: 'counter', targetValue: 10, trackingKey: 'perfect_matches' },
        isSecret: true, // Secret achievement
        displayOrder: 17,
    },
];

/**
 * Progression Achievements
 * Track XP, tiers, seasons, and prestige
 */
export const PROGRESSION_ACHIEVEMENTS: Achievement[] = [
    // Bronze
    {
        id: 'p01',
        name: 'Rising Star',
        description: 'Reach Battle Pass Tier 5',
        category: 'progression',
        tier: 'bronze',
        iconUrl: '/assets/achievements/rising_star.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'milestone', targetValue: 5, trackingKey: 'current_tier' },
        isSecret: false,
        displayOrder: 1,
    },
    {
        id: 'p02',
        name: 'XP Hunter',
        description: 'Earn 5,000 XP',
        category: 'progression',
        tier: 'bronze',
        iconUrl: '/assets/achievements/xp_hunter.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 5000, trackingKey: 'total_xp' },
        isSecret: false,
        displayOrder: 2,
    },
    {
        id: 'p03',
        name: 'Quest Starter',
        description: 'Complete 3 daily quests',
        category: 'progression',
        tier: 'bronze',
        iconUrl: '/assets/achievements/quest_starter.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 3, trackingKey: 'quests_completed' },
        isSecret: false,
        displayOrder: 3,
    },
    // Silver
    {
        id: 'p04',
        name: 'Climber',
        description: 'Reach Battle Pass Tier 15',
        category: 'progression',
        tier: 'silver',
        iconUrl: '/assets/achievements/climber.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'milestone', targetValue: 15, trackingKey: 'current_tier' },
        isSecret: false,
        displayOrder: 4,
    },
    {
        id: 'p05',
        name: 'XP Veteran',
        description: 'Earn 25,000 XP',
        category: 'progression',
        tier: 'silver',
        iconUrl: '/assets/achievements/xp_veteran.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 25000, trackingKey: 'total_xp' },
        isSecret: false,
        displayOrder: 5,
    },
    {
        id: 'p06',
        name: 'Quest Enthusiast',
        description: 'Complete 15 daily quests',
        category: 'progression',
        tier: 'silver',
        iconUrl: '/assets/achievements/quest_enthusiast.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 15, trackingKey: 'quests_completed' },
        isSecret: false,
        displayOrder: 6,
    },
    {
        id: 'p07',
        name: 'Quest Streak',
        description: 'Complete all daily quests 3 days in a row',
        category: 'progression',
        tier: 'silver',
        iconUrl: '/assets/achievements/quest_streak.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'milestone', targetValue: 3, trackingKey: 'quest_streak' },
        isSecret: false,
        displayOrder: 7,
    },
    // Gold
    {
        id: 'p08',
        name: 'Halfway Hero',
        description: 'Reach Battle Pass Tier 25',
        category: 'progression',
        tier: 'gold',
        iconUrl: '/assets/achievements/halfway_hero.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'milestone', targetValue: 25, trackingKey: 'current_tier' },
        isSecret: false,
        displayOrder: 8,
    },
    {
        id: 'p09',
        name: 'XP Champion',
        description: 'Earn 100,000 XP',
        category: 'progression',
        tier: 'gold',
        iconUrl: '/assets/achievements/xp_champion.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'counter', targetValue: 100000, trackingKey: 'total_xp' },
        isSecret: false,
        displayOrder: 9,
    },
    {
        id: 'p10',
        name: 'Quest Master',
        description: 'Complete 50 daily quests',
        category: 'progression',
        tier: 'gold',
        iconUrl: '/assets/achievements/quest_master.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'counter', targetValue: 50, trackingKey: 'quests_completed' },
        isSecret: false,
        displayOrder: 10,
    },
    // Platinum
    {
        id: 'p11',
        name: 'Battle Pass Elite',
        description: 'Reach Battle Pass Tier 40',
        category: 'progression',
        tier: 'platinum',
        iconUrl: '/assets/achievements/battle_pass_elite.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'milestone', targetValue: 40, trackingKey: 'current_tier' },
        isSecret: false,
        displayOrder: 11,
    },
    {
        id: 'p12',
        name: 'Quest Legend',
        description: 'Complete 100 daily quests',
        category: 'progression',
        tier: 'platinum',
        iconUrl: '/assets/achievements/quest_legend.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'counter', targetValue: 100, trackingKey: 'quests_completed' },
        isSecret: false,
        displayOrder: 12,
    },
    {
        id: 'p13',
        name: 'Dedication',
        description: 'Maintain a 7-day quest streak',
        category: 'progression',
        tier: 'platinum',
        iconUrl: '/assets/achievements/dedication.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'milestone', targetValue: 7, trackingKey: 'quest_streak' },
        isSecret: false,
        displayOrder: 13,
    },
    // Diamond
    {
        id: 'p14',
        name: 'Max Level',
        description: 'Reach Battle Pass Tier 50',
        category: 'progression',
        tier: 'diamond',
        iconUrl: '/assets/achievements/max_level.png',
        xpReward: TIER_REWARDS.diamond.xp,
        currencyReward: TIER_REWARDS.diamond.currency,
        requirement: { type: 'milestone', targetValue: 50, trackingKey: 'current_tier' },
        isSecret: false,
        displayOrder: 14,
    },
    {
        id: 'p15',
        name: 'Prestige Warrior',
        description: 'Prestige for the first time',
        category: 'progression',
        tier: 'diamond',
        iconUrl: '/assets/achievements/prestige_warrior.png',
        xpReward: TIER_REWARDS.diamond.xp,
        currencyReward: TIER_REWARDS.diamond.currency,
        requirement: { type: 'milestone', targetValue: 1, trackingKey: 'prestige_level' },
        isSecret: false,
        displayOrder: 15,
    },
    {
        id: 'p16',
        name: 'Ultra Prestige',
        description: 'Reach Prestige Level 5',
        category: 'progression',
        tier: 'diamond',
        iconUrl: '/assets/achievements/ultra_prestige.png',
        xpReward: TIER_REWARDS.diamond.xp,
        currencyReward: TIER_REWARDS.diamond.currency,
        requirement: { type: 'milestone', targetValue: 5, trackingKey: 'prestige_level' },
        isSecret: true, // Secret
        displayOrder: 16,
    },
];

/**
 * Social Achievements
 * Track matches played, unique opponents, and community engagement
 */
export const SOCIAL_ACHIEVEMENTS: Achievement[] = [
    // Bronze
    {
        id: 's01',
        name: 'Arena Debut',
        description: 'Play your first match',
        category: 'social',
        tier: 'bronze',
        iconUrl: '/assets/achievements/arena_debut.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 1, trackingKey: 'matches_played' },
        isSecret: false,
        displayOrder: 1,
    },
    {
        id: 's02',
        name: 'Social Butterfly',
        description: 'Play against 5 unique opponents',
        category: 'social',
        tier: 'bronze',
        iconUrl: '/assets/achievements/social_butterfly.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 5, trackingKey: 'unique_opponents' },
        isSecret: false,
        displayOrder: 2,
    },
    // Silver
    {
        id: 's03',
        name: 'Regular',
        description: 'Play 25 matches',
        category: 'social',
        tier: 'silver',
        iconUrl: '/assets/achievements/regular.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 25, trackingKey: 'matches_played' },
        isSecret: false,
        displayOrder: 3,
    },
    {
        id: 's04',
        name: 'Networker',
        description: 'Play against 20 unique opponents',
        category: 'social',
        tier: 'silver',
        iconUrl: '/assets/achievements/networker.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 20, trackingKey: 'unique_opponents' },
        isSecret: false,
        displayOrder: 4,
    },
    // Gold
    {
        id: 's05',
        name: 'Veteran',
        description: 'Play 100 matches',
        category: 'social',
        tier: 'gold',
        iconUrl: '/assets/achievements/veteran.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'counter', targetValue: 100, trackingKey: 'matches_played' },
        isSecret: false,
        displayOrder: 5,
    },
    {
        id: 's06',
        name: 'Popular Fighter',
        description: 'Play against 50 unique opponents',
        category: 'social',
        tier: 'gold',
        iconUrl: '/assets/achievements/popular_fighter.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'counter', targetValue: 50, trackingKey: 'unique_opponents' },
        isSecret: false,
        displayOrder: 6,
    },
    // Platinum
    {
        id: 's07',
        name: 'Arena Legend',
        description: 'Play 500 matches',
        category: 'social',
        tier: 'platinum',
        iconUrl: '/assets/achievements/arena_legend.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'counter', targetValue: 500, trackingKey: 'matches_played' },
        isSecret: false,
        displayOrder: 7,
    },
    {
        id: 's08',
        name: 'Community Star',
        description: 'Play against 100 unique opponents',
        category: 'social',
        tier: 'platinum',
        iconUrl: '/assets/achievements/community_star.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'counter', targetValue: 100, trackingKey: 'unique_opponents' },
        isSecret: false,
        displayOrder: 8,
    },
    // Diamond
    {
        id: 's09',
        name: 'Eternal Warrior',
        description: 'Play 1000 matches',
        category: 'social',
        tier: 'diamond',
        iconUrl: '/assets/achievements/eternal_warrior.png',
        xpReward: TIER_REWARDS.diamond.xp,
        currencyReward: TIER_REWARDS.diamond.currency,
        requirement: { type: 'counter', targetValue: 1000, trackingKey: 'matches_played' },
        isSecret: false,
        displayOrder: 9,
    },
];

/**
 * Collection Achievements
 * Track cosmetics, shop purchases, and inventory
 */
export const COLLECTION_ACHIEVEMENTS: Achievement[] = [
    // Bronze
    {
        id: 'col01',
        name: 'First Purchase',
        description: 'Buy your first item from the shop',
        category: 'collection',
        tier: 'bronze',
        iconUrl: '/assets/achievements/first_purchase.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 1, trackingKey: 'shop_purchases' },
        isSecret: false,
        displayOrder: 1,
    },
    {
        id: 'col02',
        name: 'Fashionista',
        description: 'Own 3 cosmetic items',
        category: 'collection',
        tier: 'bronze',
        iconUrl: '/assets/achievements/fashionista.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 3, trackingKey: 'cosmetics_owned' },
        isSecret: false,
        displayOrder: 2,
    },
    {
        id: 'col03',
        name: 'Shard Saver',
        description: 'Earn 500 Clash Shards',
        category: 'collection',
        tier: 'bronze',
        iconUrl: '/assets/achievements/shard_saver.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 500, trackingKey: 'total_shards_earned' },
        isSecret: false,
        displayOrder: 3,
    },
    // Silver
    {
        id: 'col04',
        name: 'Shop Regular',
        description: 'Make 5 shop purchases',
        category: 'collection',
        tier: 'silver',
        iconUrl: '/assets/achievements/shop_regular.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 5, trackingKey: 'shop_purchases' },
        isSecret: false,
        displayOrder: 4,
    },
    {
        id: 'col05',
        name: 'Style Icon',
        description: 'Own 10 cosmetic items',
        category: 'collection',
        tier: 'silver',
        iconUrl: '/assets/achievements/style_icon.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 10, trackingKey: 'cosmetics_owned' },
        isSecret: false,
        displayOrder: 5,
    },
    {
        id: 'col06',
        name: 'Shard Collector',
        description: 'Earn 2,500 Clash Shards',
        category: 'collection',
        tier: 'silver',
        iconUrl: '/assets/achievements/shard_collector.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 2500, trackingKey: 'total_shards_earned' },
        isSecret: false,
        displayOrder: 6,
    },
    // Gold
    {
        id: 'col07',
        name: 'Big Spender',
        description: 'Make 15 shop purchases',
        category: 'collection',
        tier: 'gold',
        iconUrl: '/assets/achievements/big_spender.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'counter', targetValue: 15, trackingKey: 'shop_purchases' },
        isSecret: false,
        displayOrder: 7,
    },
    {
        id: 'col08',
        name: 'Collector',
        description: 'Own 25 cosmetic items',
        category: 'collection',
        tier: 'gold',
        iconUrl: '/assets/achievements/collector.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'counter', targetValue: 25, trackingKey: 'cosmetics_owned' },
        isSecret: false,
        displayOrder: 8,
    },
    {
        id: 'col09',
        name: 'Rare Find',
        description: 'Own an Epic or Legendary cosmetic',
        category: 'collection',
        tier: 'gold',
        iconUrl: '/assets/achievements/rare_find.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'milestone', targetValue: 1, trackingKey: 'epic_or_legendary_owned' },
        isSecret: false,
        displayOrder: 9,
    },
    // Platinum
    {
        id: 'col10',
        name: 'Whale',
        description: 'Make 50 shop purchases',
        category: 'collection',
        tier: 'platinum',
        iconUrl: '/assets/achievements/whale.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'counter', targetValue: 50, trackingKey: 'shop_purchases' },
        isSecret: false,
        displayOrder: 10,
    },
    {
        id: 'col11',
        name: 'Shard Hoarder',
        description: 'Earn 10,000 Clash Shards',
        category: 'collection',
        tier: 'platinum',
        iconUrl: '/assets/achievements/shard_hoarder.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'counter', targetValue: 10000, trackingKey: 'total_shards_earned' },
        isSecret: false,
        displayOrder: 11,
    },
    // Diamond
    {
        id: 'col12',
        name: 'Complete Collection',
        description: 'Own 50 cosmetic items',
        category: 'collection',
        tier: 'diamond',
        iconUrl: '/assets/achievements/complete_collection.png',
        xpReward: TIER_REWARDS.diamond.xp,
        currencyReward: TIER_REWARDS.diamond.currency,
        requirement: { type: 'counter', targetValue: 50, trackingKey: 'cosmetics_owned' },
        isSecret: false,
        displayOrder: 12,
    },
    {
        id: 'col13',
        name: 'Legendary Collector',
        description: 'Own 3 Legendary cosmetics',
        category: 'collection',
        tier: 'diamond',
        iconUrl: '/assets/achievements/legendary_collector.png',
        xpReward: TIER_REWARDS.diamond.xp,
        currencyReward: TIER_REWARDS.diamond.currency,
        requirement: { type: 'counter', targetValue: 3, trackingKey: 'legendary_owned' },
        isSecret: true, // Secret
        displayOrder: 13,
    },
];

/**
 * Mastery Achievements
 * Track survival mode, combo challenges, and category completion
 */
export const MASTERY_ACHIEVEMENTS: Achievement[] = [
    // Bronze
    {
        id: 'm01',
        name: 'Survival Initiate',
        description: 'Complete 5 waves in Survival Mode',
        category: 'mastery',
        tier: 'bronze',
        iconUrl: '/assets/achievements/survival_initiate.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'milestone', targetValue: 5, trackingKey: 'max_survival_waves' },
        isSecret: false,
        displayOrder: 1,
    },
    {
        id: 'm02',
        name: 'Achievement Hunter',
        description: 'Unlock 5 achievements',
        category: 'mastery',
        tier: 'bronze',
        iconUrl: '/assets/achievements/achievement_hunter.png',
        xpReward: TIER_REWARDS.bronze.xp,
        currencyReward: TIER_REWARDS.bronze.currency,
        requirement: { type: 'counter', targetValue: 5, trackingKey: 'achievements_unlocked' },
        isSecret: false,
        displayOrder: 2,
    },
    // Silver
    {
        id: 'm03',
        name: 'Survival Veteran',
        description: 'Complete 10 waves in Survival Mode',
        category: 'mastery',
        tier: 'silver',
        iconUrl: '/assets/achievements/survival_veteran.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'milestone', targetValue: 10, trackingKey: 'max_survival_waves' },
        isSecret: false,
        displayOrder: 3,
    },
    {
        id: 'm04',
        name: 'Achievement Addict',
        description: 'Unlock 20 achievements',
        category: 'mastery',
        tier: 'silver',
        iconUrl: '/assets/achievements/achievement_addict.png',
        xpReward: TIER_REWARDS.silver.xp,
        currencyReward: TIER_REWARDS.silver.currency,
        requirement: { type: 'counter', targetValue: 20, trackingKey: 'achievements_unlocked' },
        isSecret: false,
        displayOrder: 4,
    },
    // Gold
    {
        id: 'm05',
        name: 'Survival Expert',
        description: 'Complete 15 waves in Survival Mode',
        category: 'mastery',
        tier: 'gold',
        iconUrl: '/assets/achievements/survival_expert.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'milestone', targetValue: 15, trackingKey: 'max_survival_waves' },
        isSecret: false,
        displayOrder: 5,
    },
    {
        id: 'm06',
        name: 'Combat Mastery',
        description: 'Unlock all Bronze combat achievements',
        category: 'mastery',
        tier: 'gold',
        iconUrl: '/assets/achievements/combat_mastery.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'collection', targetValue: 4, trackingKey: 'combat_bronze_unlocked' },
        isSecret: false,
        displayOrder: 6,
    },
    {
        id: 'm07',
        name: 'Achievement Collector',
        description: 'Unlock 40 achievements',
        category: 'mastery',
        tier: 'gold',
        iconUrl: '/assets/achievements/achievement_collector.png',
        xpReward: TIER_REWARDS.gold.xp,
        currencyReward: TIER_REWARDS.gold.currency,
        requirement: { type: 'counter', targetValue: 40, trackingKey: 'achievements_unlocked' },
        isSecret: false,
        displayOrder: 7,
    },
    // Platinum
    {
        id: 'm08',
        name: 'Survival Champion',
        description: 'Complete all 20 waves in Survival Mode',
        category: 'mastery',
        tier: 'platinum',
        iconUrl: '/assets/achievements/survival_champion.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'milestone', targetValue: 20, trackingKey: 'max_survival_waves' },
        isSecret: false,
        displayOrder: 8,
    },
    {
        id: 'm09',
        name: 'Category Master',
        description: 'Unlock all achievements in any one category',
        category: 'mastery',
        tier: 'platinum',
        iconUrl: '/assets/achievements/category_master.png',
        xpReward: TIER_REWARDS.platinum.xp,
        currencyReward: TIER_REWARDS.platinum.currency,
        requirement: { type: 'milestone', targetValue: 1, trackingKey: 'categories_completed' },
        isSecret: false,
        displayOrder: 9,
    },
    // Diamond
    {
        id: 'm10',
        name: 'Completionist',
        description: 'Unlock 60 achievements',
        category: 'mastery',
        tier: 'diamond',
        iconUrl: '/assets/achievements/completionist.png',
        xpReward: TIER_REWARDS.diamond.xp,
        currencyReward: TIER_REWARDS.diamond.currency,
        requirement: { type: 'counter', targetValue: 60, trackingKey: 'achievements_unlocked' },
        isSecret: false,
        displayOrder: 10,
    },
    {
        id: 'm11',
        name: 'Ultimate Champion',
        description: 'Unlock all achievements in all categories',
        category: 'mastery',
        tier: 'diamond',
        iconUrl: '/assets/achievements/ultimate_champion.png',
        xpReward: TIER_REWARDS.diamond.xp * 2, // Double reward for ultimate achievement
        currencyReward: TIER_REWARDS.diamond.currency * 2,
        badgeReward: 'ultimate_champion_badge',
        requirement: { type: 'milestone', targetValue: 5, trackingKey: 'categories_completed' },
        isSecret: true, // Secret ultimate achievement
        displayOrder: 11,
    },
];

/**
 * All achievements combined
 */
export const ALL_ACHIEVEMENTS: Achievement[] = [
    ...COMBAT_ACHIEVEMENTS,
    ...PROGRESSION_ACHIEVEMENTS,
    ...SOCIAL_ACHIEVEMENTS,
    ...COLLECTION_ACHIEVEMENTS,
    ...MASTERY_ACHIEVEMENTS,
];

/**
 * Get achievements by category
 */
export function getAchievementsByCategory(category: AchievementCategory): Achievement[] {
    switch (category) {
        case 'combat':
            return COMBAT_ACHIEVEMENTS;
        case 'progression':
            return PROGRESSION_ACHIEVEMENTS;
        case 'social':
            return SOCIAL_ACHIEVEMENTS;
        case 'collection':
            return COLLECTION_ACHIEVEMENTS;
        case 'mastery':
            return MASTERY_ACHIEVEMENTS;
        default:
            return [];
    }
}

/**
 * Get an achievement by ID
 */
export function getAchievementById(id: string): Achievement | undefined {
    return ALL_ACHIEVEMENTS.find((a) => a.id === id);
}

/**
 * Get achievement counts per category
 */
export function getAchievementCounts(): Record<AchievementCategory | 'total', number> {
    return {
        combat: COMBAT_ACHIEVEMENTS.length,
        progression: PROGRESSION_ACHIEVEMENTS.length,
        social: SOCIAL_ACHIEVEMENTS.length,
        collection: COLLECTION_ACHIEVEMENTS.length,
        mastery: MASTERY_ACHIEVEMENTS.length,
        total: ALL_ACHIEVEMENTS.length,
    };
}

/**
 * Get achievements by tier
 */
export function getAchievementsByTier(tier: AchievementTier): Achievement[] {
    return ALL_ACHIEVEMENTS.filter((a) => a.tier === tier);
}
